version: '3.6'

services:
  web:
    image: hut6/bump-run:${TAG-latest}
    ports:
      - 80:80
    deploy:
      replicas: 2
      update_config:
        failure_action: rollback
        order: start-first
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 100M
